name: "Deploy Site"

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: "Deploy Site"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}-${{ hashFiles('**.[jt]sx?') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}-

      - uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: yarn

      - run: yarn install

      - run: yarn build

      - run: yarn export

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: gh-pages
          folder: out
          single-commit: true
