name: "Deploy Site"

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    name: "Deploy Site"
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/configure-pages@v4
        with:
          static_site_generator: next

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn

      - name: Restore cache
        uses: actions/cache@v3
        with:
          path: |
            .next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}-

      - run: yarn install

      - run: yarn build

      - uses: actions/upload-pages-artifact@v2
        with:
          path: ./out

      - uses: actions/deploy-pages@v3
        id: deployment
