name: "Deploy Site"

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: "Deploy Site"
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/configure-pages@v4
        with:
          static_site_generator: next

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn

      - run: yarn install

      - run: yarn build

      - run: yarn export

      - uses: actions/upload-pages-artifact@v2
        with:
          path: ./out

      - uses: actions/deploy-pages@v3
        id: deployment
